######## DB variable #########
spring.datasource.url={DB_URL:}
spring.datasource.username=${DB_USER:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

########## Delais d'expiration (en millisecondes) #############
# 15 minutes pour l'Access Token, 7 jours pour le Refresh Token
jwt.secreteKey=${JWT_SECRET_KEY}
jwt.expire=900000
jwt.refreshExpire=604800000

####### Google OAuth2 Config ###############
spring.security.oauth2.client.registration.google.client-id=${GL_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GL_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
